name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - smoke
        - regression
      browser:
        description: 'Browser to test'
        required: false
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox
        - webkit
        - all
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: dev
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      TIMEOUT: ${{ vars.TIMEOUT }}
      SLOW_MO: ${{ vars.SLOW_MO }}
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ vars.PASSWORD }}
      TEST_PASSWORD: ${{ vars.TEST_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Display test configuration
      run: |
        echo "Test Type: ${{ github.event.inputs.test_type || 'all' }}"
        echo "Browser: ${{ github.event.inputs.browser || 'chromium' }}"
        echo "Base URL: $BASE_URL"
        echo "Username: $USERNAME"
        echo "Timeout: $TIMEOUT"
    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.test_type }}" = "smoke" ]; then
          npx playwright test --grep "smoke" --project=${{ github.event.inputs.browser || 'chromium' }}
        elif [ "${{ github.event.inputs.test_type }}" = "regression" ]; then
          npx playwright test --grep "regression" --project=${{ github.event.inputs.browser || 'chromium' }}
        else
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            npx playwright test
          else
            npx playwright test --project=${{ github.event.inputs.browser || 'chromium' }}
          fi
        fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ github.event.inputs.test_type || 'all' }}-${{ github.event.inputs.browser || 'chromium' }}
        path: playwright-report/
        retention-days: 30
